### ISSUE TITLE
enable retrying in mput/put in repocli by default

### ISSUE THREAD

**Issue by achetverikov** [Donders-Institute/dr-tools#12]
It'd be nice if by default put/mput would try to retry the upload on error. I know that there is a parameter for that, but I only learned about it after seeing the errors due to connection failure in the log for a massive transfer job.

**Comment by hurngchunlee** [comment]
@achetverikov this was also suggested by @benglitz.

I have just make the default `maxretry` to 2 (in total 3 attempts).  See https://github.com/Donders-Institute/dr-tools/commit/ea2a77688fb02a0d948ad8fdb464008d6944c1ca
