### ISSUE TITLE
update readme for repocli 

### ISSUE THREAD

**Issue by achetverikov** [Donders-Institute/dr-tools#13]
The readme says: "The WebDAV path should always be in form of the absolute path (i.e. started with /); while the local path can be in a format recognized by the shell.". Relative paths (starting with ./) seem to work fine as WebDAV paths for me.

**Comment by hurngchunlee** [comment]
@achetverikov I have adjusted the README accordingly.  See https://github.com/Donders-Institute/dr-tools/commit/19d6d5b26e7144c47a9f5cd4735af9ee041ac950
