### ISSUE TITLE
errors 500 and 401

### ISSUE THREAD

**Issue by Aleman-Z** [Donders-Institute/dr-tools#14]
Dear developer, 
I would like to ask why I get these errors when I use **_put_** to upload data  to a repository in /dcn and how to deal with them.
1)	Error 500:  error:cannot stat … at the repository: PROPFIND … : 500
2)	Error 401:  error:cannot write … to the repository: Authorize https://webdav.data.donders.ru.nl/: 401

I add here the complete outputs I copied from the errors text file.
1)	Error 500 
/media/genzel/MD04_RAT_RIPPLE/rat/Rat_OS_Ephys/Rat_OS_Ephys_Rat13_344994/Rat_OS_Ephys_Rat13_344994_SD13_OR_SD_N_13-14_06_2019/test/2019-06-14_11-52-42_trial6/100_CH18_0.continuous error:cannot stat /dcn/DAC_626830_0009_541/OS_basic/Rat_OS_Ephys_Rat13_344994/Rat_OS_Ephys_Rat13_344994_SD13_OR_SD_N_13-14_06_2019/test/2019-06-14_11-52-42_trial6/100_CH18_0.continuous at the repository: PROPFIND /dcn/DAC_626830_0009_541/OS_basic/Rat_OS_Ephys_Rat13_344994/Rat_OS_Ephys_Rat13_344994_SD13_OR_SD_N_13-14_06_2019/test/2019-06-14_11-52-42_trial6/100_CH18_0.continuous: 500

2)	Error 401
/media/genzel/MD04_RAT_RIPPLE/rat/Rat_OS_Ephys/Rat_OS_Ephys_Rat13_344994/Rat_OS_Ephys_Rat13_344994_SD1_CON_14-13_05_2019/2019-05-13_14-41-35_trial5/100_CH56_0.continuous error:cannot write /dcn/DAC_626830_0009_541/OS_basic/Rat_OS_Ephys_Rat13_344994/Rat_OS_Ephys_Rat13_344994_SD1_CON_14-13_05_2019/2019-05-13_14-41-35_trial5/100_CH56_0.continuous to the repository: Authorize https://webdav.data.donders.ru.nl/: 401

Thanks in advance,
Adrian.

**Comment by hurngchunlee** [comment]
@Aleman-Z please use the datasupport@donders.ru.nl for such type of questions/issues.  It is not specific to the client tool but the Donders Repository server.

I am closing the issue now.

**Comment by Aleman-Z** [comment]
ok thank you for letting me know.
