### ISSUE TITLE
Folder size and number of files. 

### ISSUE THREAD

**Issue by Aleman-Z** [Donders-Institute/dr-tools#15]
Hi, 
I wonder if a command for finding the size of a folder uploaded to repocli could be implemented? 
As well as another one for finding the total number of files within a folder. 
I normally do this with `df -h ` and `ls | wc -l` respectively on linux. 
I think these would be useful functions when trying to compare client and server copies of the data.

Best regards, 
Adrian.

**Comment by hurngchunlee** [comment]
@Aleman-Z I assume you want to be able to get the size and number of files in a remote folder (i.e. WebDAV collection) recursively.  If it is the case, it is already possible to do it with repocli in a shell script.

Here is a quick example:  https://github.com/Donders-Institute/dr-tools/blob/main/cmd/repocli/size.sh

**Comment by Aleman-Z** [comment]
thank you @hurngchunlee  , it works well!
I have adapted the last bit of the code to convert the size from bytes to more human friendly units (KiB, MiB,  etc) whenever possible.

**Comment by Aleman-Z** [comment]
thank you @hurngchunlee , it works well!
I have adapted the last bit of the code to convert the size from bytes to more human friendly units (KiB, MiB, etc) whenever it is possible. 
[https://gist.github.com/Aleman-Z/d244caaf0171137d10d1db7aa1f5e1ca#file-size-sh-L60-L83](https://gist.github.com/Aleman-Z/d244caaf0171137d10d1db7aa1f5e1ca#file-size-sh-L60-L83)
Cheers!
