### ISSUE TITLE
Make error across platforms

### ISSUE THREAD

**Issue by EsamGhaleb** [Donders-Institute/dr-tools#18]
I always get this error in Linux and Mac:

> GOPATH=home/go GOOS=linux GO111MODULE=on go install --ldflags="-X 'github.com/Donders-Institute/dr-tools/internal/cmd/version.Version=master'" github.com/Donders-Institute/dr-tools/...
> /bin/sh: go: command not found
> make: *** [build] Error 127

Why does it require ''go'' to be already installed?

**Comment by hurngchunlee** [comment]
@EsamGhaleb if you just need the binary, you can just download it from [the release page](https://github.com/Donders-Institute/dr-tools/releases).  Go compiler is only needed for compiling the source code to the binary.

**Comment by EsamGhaleb** [comment]
Thanks a lot for the quick reply. I get the following error: “repocli.darwin_arm64” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information." even though I changed the permission. Should it work directly?

**Comment by hurngchunlee** [comment]
https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by EsamGhaleb** [comment]
Thanks a lot. This saved me a lot of manual work. I am now downloading the dataset
