### ISSUE TITLE
As a user, I would like to specify multiple sources for `get` and `put` subcommands

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/dr-tools#2]
A common use case for me is that I only need a subset of a data repository, but the data I need are spread out over the entire directory tree of the repo.

I would like to give a list of files to get and give a destination directory (i.e Subject05), and to have the result that the copied data would be placed in a directory tree that mirrors that of the data repository. This is a behavior similar to the  `--parents` option in the GNU version of the `cp` command.

**Comment by robertoostenveld** [comment]
Zooming out and considering the https://en.wikipedia.org/wiki/Not_invented_here tendency... 

Rather than implementing all sorts of use cases in a self-implemented (and to-be-maintained and documented) application, why not support [datalad](https://www.datalad.org) for all collections on the Donders Repository? It has an implementation, user interface and documentation that are developed  and supported by a much larger and experienced team. The open-access published collections can already be accessed with with datalad through https://github.com/Donders-Institute-Data. OpenNeuro also has all its datasets accessible with datalad.

**Comment by hurngchunlee** [comment]
@robertoostenveld I see your point, and definitely datalad is something to look at.  However, I don't see strong overlap between the tool provided in this repo (primarily the [repocli](https://github.com/Donders-Institute/dr-tools/tree/main/cmd/repocli)) and datalad.

What triggered me to develop this tool is to have an efficient way to organize data easily using the supported webdav interface.  On top of puting/getting data to/from collections, it is more about navigating through collections, copying, renaming, removing data within the repository.  I have been using it for a while privately, until recently some HPC users come to ask similar question which makes me to decide to make it also available publicly.

This tool, to my best knowledge, is an alternative to cadaver.  Apart from the fact that cadaver is "no-longer being maintained", it has few additional features:

- more efficient way for operating on many files,
- auto-completion,
- cross-platform

**Comment by hurngchunlee** [comment]
@robertoostenveld I see your point, and definitely datalad is something to look at.  However, I don't see strong overlap between the tool provided in this repo (primarily the [repocli](https://github.com/Donders-Institute/dr-tools/tree/main/cmd/repocli)) and datalad.

What triggered me to develop this tool is to have an efficient way to organize data easily using the supported webdav interface.  On top of puting/getting data to/from collections, it is more about navigating through collections, copying, renaming, removing data within the repository.  I have been using it for a while privately, until recently some HPC users come to ask similar question which makes me to decide to make it also available publicly.

This tool, to my best knowledge, is an alternative to cadaver.  Apart from the fact that cadaver is "no-longer being maintained", it has few additional features:

- more efficient way for operating on many files,
- auto-completion,
- cross-platform

**Comment by robertoostenveld** [comment]
It is certainly nice to have another and better webdav client to interact with the DR. But I wonder whether we (at the DCCN) should not be a bit more ambitious and make a bigger step to improve the ease and quality of data management. But that is not something that we need to discuss here in further detail. I was simply triggered by the request to `put` or `get` multiple data sources/files over webdav, which datalad already has (e.g. [push](http://docs.datalad.org/en/stable/generated/man/datalad-push.html)).

**Comment by hurngchunlee** [comment]
@robertoostenveld shall we move the discussion about datalad to a separate issue (can be in this repo)?

btw, after playing around datalad today, I seem to know how to create a datalad dataset from an existing collection.  Since I don't know how advance you (and our researchers) are in this context, I wonder if it is something useful to share (or build a script for doing that) ...

**Comment by robertoostenveld** [comment]
I think we should definitely build up and share expertise on this! I have a script that is doing it for public collections (the ones on https://github.com/Donders-Institute-Data). That is now already for three weeks churning through a public collection that has some 600GB of nifti files (downloading over webdav one by one).

**Comment by hurngchunlee** [comment]
> I think we should definitely build up and share expertise on this! I have a script that is doing it for public collections (the ones on https://github.com/Donders-Institute-Data). That is now already for three weeks churning through a public collection that has some 600GB of nifti files (downloading over webdav one by one).

Cool! I just initiated a new issue #3.  Let's exchange information and discuss further there.

**Comment by hurngchunlee** [comment]
The feature has been added to [release 0.2.0](https://github.com/Donders-Institute/dr-tools/releases/tag/0.2.0).
