### ISSUE TITLE
failure to transfer large (~100GB) file

### ISSUE THREAD

**Issue by benglitz** [Donders-Institute/dr-tools#6]
When trying to transfer files larger than a few gigabytes (not sure where the exact threshold is, but maybe around 50GB?) then the transfer repeatedly fails, sometimes without an error message.

**Comment by hurngchunlee** [comment]
@benglitz sometime ago, you reported that you managed to upload ~100GB file with repocli.  I suppose this issue is either fixed or not directly related with repocli.  I am closing it for now.  If you run into the same issue, feel free to reopen it.
