### ISSUE TITLE
differential, automatic file transfer on partially transferred folder tree, based on file attributes

### ISSUE THREAD

**Issue by benglitz** [Donders-Institute/dr-tools#7]
It would be great to have the possibility to 'safely' run a transfer on a partially transferred directory tree, e.g. if only a part was transferred, it would be great to be able to just rerun the upload command on the base directory and repocli would identify which files still need to be transferred, e.g. based on a comparison of the size/modification date of the source and target files.

**Comment by hurngchunlee** [comment]
@benglitz I have implemented it in such that a file is considered ___existing___ at the destination if

- the path at the destination exists, and
- file at destination has the same size as the file at source, and
- file at destination has modification time later than the file at source

If there is an error getting the file information and the error is not `FileNotFound`, the file is also considered "existing" at the destination to prevent accidental file overwrite. 

If a file is considered existing, the put/get operation will skip it unless you have the `-f` flag specified to overwrite existing files.
