### ISSUE TITLE
send email on completion of file transfer

### ISSUE THREAD

**Issue by benglitz** [Donders-Institute/dr-tools#8]
Often the uploads take a long time, and one needs to very frequently check whether they are finished. It would be great to add the possibility to send an email upon completion of the upload, maybe even with the collected text output during the upload.

**Comment by hurngchunlee** [comment]
I would not add this feature to repocli itself.  Since repocli can be run as a shell command, it can be easily chained up (or scripted) with other programs to send out email when it is finished.
